### ISSUE TITLE
Turkish Bank Name Change

### ISSUE THREAD

**Issue by karamusluk** [ibanapi/data#1]
The Turkish Bank on that address https://ibanapi.com/bank/1415/turkiye-garanti-bankasi-a.s. has changed to Garanti BBVA

**Comment by ibanapi** [comment]
Thank you @karamusluk  for reporting this, our team working on the update now.

**Comment by ibanapi** [comment]
Bank Name changed, thank you for the report.

**Comment by karamusluk** [comment]
FYI,
Also the BIC /SWIFT code seems to be wrong as well.
https://wise.com/gb/swift-codes/countries/turkey/garanti-bankasi-swift-code

**Comment by ibanapi** [comment]
Hi @karamusluk the BIC/SWIFT is correct, however, the XXX in the BIC are for the branch related.
