### ISSUE TITLE
Banks not listed 

### ISSUE THREAD

**Issue by msshahanshah** [ibanapi/data#2]
Banque Internationale pour le Commerce et l'Industrie de la Côte d'Ivoire: CI006
Societe Ivoirienne de Banque: CI007
Société Générale Côte d'Ivoire: CI008
Bank Of Africa Côte d'Ivoire: CI032
Banque Atlantique Côte d'Ivoire: CI034
NSIA Banque Côte d'Ivoire: CI042
Ecobank Côte d'Ivoire: CI059
Banque de l'Habitat de Côte d'Ivoire: CI068
Banque Nationale d'Investissement: CI092
Standard Chartered Bank Côte d'Ivoire: CI097
AFRILAND FIRST BANK Côte d'Ivoire: CI106
Versus Bank S.A: CI112
Citibank - Côte d'Ivoire: CI118
ORABANK Côte d'Ivoire: CI121
Bridge Bank Group Côte d'Ivoire: CI131
United Bank for Africa CI: CI150
Banque Sahélo-Saharienne pour l'Investissement et le Commerce Côte d'Ivoire: CI154
Banque Populaire de Côte d'Ivoire: CI155
Diamond Bank Côte d'Ivoire: CI158
BGFI BANK COTE D'IVOIRE: CI162
Guaranty Trust Bank Côte d'Ivoire: CI163
Coris Bank International Côte d'Ivoire: CI166
Banque De l'Union Côte d'Ivoire: CI180
Banque Malienne de Solidarité, Succursale de Côte d'Ivoire: CI188
Banque Régionale de Marchés, Succursale de Côte d'Ivoire: CI194
Stanbic Bank: CI198
Banque d'Abidjan: CI201
Mansa Bank: CI211
Orange Abidjan Compagnie: CI214

**Comment by ibanapi** [comment]
That was updated, thank you for the report.

This bank no BIC available, so was not added for now **Banque Populaire de Côte d'Ivoire**
