### ISSUE TITLE
NOLADE21HIK validations

### ISSUE THREAD

**Issue by Cardmarket** [ibanapi/data#3]
Some IBANS for the Sparkasse Hildesheim Goslar Peine (https://ibanapi.com/bank/2959/sparkasse-hildesheim-goslar-peine) are reported as invalid with
`{"result":411,"message":"Invalid Account Number Checksum"}`
although valid and real bank accounts.

**Comment by ibanapi** [comment]
Can you please share with us one of which to run it through?

Thanks.

**Comment by Cardmarket** [comment]
DE51259501300096301858

**Comment by ibanapi** [comment]
Thank you for reporting this, it is a specific issue for this PLZ, it seems the alteration to the algorithm in the latest update was not added to the system.

This has been fixed now.
