### ISSUE TITLE
EEUHEE2X validations

### ISSUE THREAD

**Issue by Cardmarket** [ibanapi/data#4]
Some IBANS for the AS SEB Bank (https://ibanapi.com/bank/1671/as-seb-pank) are reported as invalid with
{"result":411,"message":"Invalid Account Number Checksum"}
although valid and real bank accounts.

**Comment by ibanapi** [comment]
Can you please share with us an example?

**Comment by Cardmarket** [comment]
EE041010010484832010

**Comment by ibanapi** [comment]
Thank you for reporting this, the issue was in the checksum algorithm, where it expects 14 digits account number, while on the Swift documentation it says the Estonian account number is 12 digits.

This is fixed now.
