### ISSUE TITLE
Request failed for this IBAN FR761599902217XXXXXXXXXXXXX

### ISSUE THREAD

**Issue by isaac-oulai** [ibanapi/data#7]
X = account number 
{
  "timestamp": "2023-12-14T13:51:52.107+00:00",
  "status": 500,
  "error": "Internal Server Error",
  "path": "/ibanApi/dataFromIban/FR761599902217XXXXXXXXXXXXX/true"
}

Expected 

bank name :  CREDIT MUTUEL
BIC : CMCIFR2A
Branch code : XXX

**Comment by isaac-oulai** [comment]
The bank exist in your database 

![image](https://github.com/ibanapi/data/assets/142985427/dd53109a-647e-4e65-8ee1-1022d0d6aa67)

**Comment by ibanapi** [comment]
Thank you, Isaac, for bringing this to our attention, according to the team, this was taken care of, and the above 500 internal error is not from the API side.
